import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Jost, Bebas_Neue } from 'next/font/google';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


// Initialize the fonts
const jost = Jost({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

const bebasNeue = Bebas_Neue({
  subsets: ['latin'],
  weight: ['400']
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${jost.className} bg-black text-white`}>
        {children}
      </body>
    </html>
  );
}
